#!/bin/bash

################################################################################
# opm - Java 7 remover                                                         #
#                                                                              #
# Remove java7-32bit                                                           #
#                                                                              #
################################################################################

if [ $# -ne 1 ]
then
	echo "Usage: `basename $0` {VERSION}"
	exit $E_BADARGS
else
	VERSION="$1"
	echo "Start remove java7, 32bit, version $VERSION"
	
	SUBFOLDER="java7-32/$VERSION"
	OPTFOLDER="/opt/opm/$SUBFOLDER"

	# TODO: REUSE
	if [ -d $OPTFOLDER ]
	then
		rm -rf $OPTFOLDER
		BINFOLDER="/opt/opm/bin"
		FILES=`find -L $BINFOLDER `
		for f in $FILES
		do
			LINK=`readlink $f`
			GREP_OUT=`echo "$LINK" | grep "$OPTFOLDER"`
			if [ "$GREP_OUT" != "" ]
			then
				rm $f;
			fi
		done
		echo "Finished remove java7, 32bit, version $VERSION"
	else
		echo "java7, 32bit $VERSION is not installed!"
	fi
fi

